# Generated by Django 4.1.2 on 2022-10-30 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_category_product_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='detial',
            new_name='detail',
        ),
    ]
